require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require './lib/item_repository.rb'
require './lib/sales_engine'
require './lib/sales_analyst'
require './lib/invoice_repository'
require 'csv'
require 'pry-state'
require './lib/invoice_item_repository'
require './lib/transaction_repository'
require './lib/customer_repository'
