require 'simplecov'
SimpleCov.start
require 'csv'
require 'minitest/autorun'
require 'minitest/pride'
require 'bigdecimal'
require 'time'
require 'minitest/unit'
require 'mocha/minitest'
require './lib/merchant'
require './lib/merchant_repository'
require './lib/sales_engine'
require './lib/item_repository'
require './lib/item'
require './lib/sales_analyst'
