require 'pry'
require 'minitest/autorun'
require 'minitest/pride'
require 'simplecov'
require 'bigdecimal'
require 'time'
require 'CSV'
SimpleCov.start
# Include future files that are required underneath SimpleCov, so it has started and they are tabulated in the coverage.
require './lib/merchant'
require './lib/item'
require './lib/merchant'
require './lib/merchant_repository'
require './lib/item_repository'
require './lib/sales_engine'
require './lib/sales_analyst'
require './lib/repository'
require './lib/invoice_repository'
