require "simplecov"
SimpleCov.start

require "./spec/merchant_spec"
require "./spec/merchant_repo_spec"
require "./spec/invoice_spec"
require "./spec/invoice_repo_spec"
require "./spec/item_spec"
require "./spec/item_repo_spec"
require "./spec/customer_spec"
require "./spec/customer_repo_spec"
require "./spec/sales_engine_spec"
require "./spec/sales_analyst_spec"
require "./spec/transaction_spec"
require "./spec/transaction_repo_spec"
require "./spec/invoice_item_spec"
require "./spec/invoice_item_repo_spec"
